name: testeseki
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.16.0
  emailjs: ^1.3.0
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  flutter:
    sdk: flutter
  http: ^1.2.1
  logger: ^2.2.0
  mailer: ^6.1.0
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1
  intl: ^0.19.0
  internet_connection_checker_plus: ^2.3.0
  shimmer: ^3.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/userlogin.png
    - images/cadeado.png
    - images/usuario.png
    - images/redefinir_senha.png
    - images/empresa.png
    - assets/no_internet.png
    - images/setor.png
    
